backend:
  embeddings: "ollama"  # or "ollama"
  generation: "ollama"  # or "openai"
ollama:
  host: "http://localhost:11434"
  gen_model: "qwen2.5"
  emb_model: "mxbai-embed-large"
openai:
  api_key: "your-key"
  gen_model: "gpt-3.5-turbo"
  emb_model: "text-embedding-ada-002"
database:
  url: "postgres://user:password@localhost:5432/dbname?sslmode=disable"
log_level: "info"