name: Main
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
permissions:
  contents: read
  packages: write

jobs:
    test:
        name: Unit testing
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
              with:
                go-version-file: 'go.mod'
                cache: false
            - name: Run go mod tidy
              run: go mod tidy
            - name: Run tests
              run: go test -cover ./..
    golangci-lint:
      name: Run golangci-lint
      runs-on: ubuntu-latest
      permissions:
        # Required: allow read access to the content for analysis.
        contents: read
        # Optional: allow read access to pull request. Use with `only-new-issues` option.
        pull-requests: read
        # Optional: Allow write access to checks to allow the action to annotate code in the PR.
        checks: write
      steps:
        - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
          with:
            go-version-file: 'go.mod'
            cache: false
        - name: golangci-lint
          uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
